[1mdiff --git a/DugunSalonuKiralama/.vs/DugunSalonuKiralama/FileContentIndex/3bfbdb69-0fb1-4237-bffa-069ad677a0ba.vsidx b/DugunSalonuKiralama/.vs/DugunSalonuKiralama/FileContentIndex/3bfbdb69-0fb1-4237-bffa-069ad677a0ba.vsidx[m
[1mdeleted file mode 100644[m
[1mindex 3db9340..0000000[m
Binary files a/DugunSalonuKiralama/.vs/DugunSalonuKiralama/FileContentIndex/3bfbdb69-0fb1-4237-bffa-069ad677a0ba.vsidx and /dev/null differ
[1mdiff --git a/DugunSalonuKiralama/.vs/DugunSalonuKiralama/FileContentIndex/3d30a25b-c003-498d-8e05-e25a98d1b3cd.vsidx b/DugunSalonuKiralama/.vs/DugunSalonuKiralama/FileContentIndex/3d30a25b-c003-498d-8e05-e25a98d1b3cd.vsidx[m
[1mdeleted file mode 100644[m
[1mindex 3e09601..0000000[m
Binary files a/DugunSalonuKiralama/.vs/DugunSalonuKiralama/FileContentIndex/3d30a25b-c003-498d-8e05-e25a98d1b3cd.vsidx and /dev/null differ
[1mdiff --git a/DugunSalonuKiralama/.vs/DugunSalonuKiralama/FileContentIndex/5bca156e-dcae-4543-9a18-c9afb0167f07.vsidx b/DugunSalonuKiralama/.vs/DugunSalonuKiralama/FileContentIndex/5bca156e-dcae-4543-9a18-c9afb0167f07.vsidx[m
[1mdeleted file mode 100644[m
[1mindex bb2f222..0000000[m
Binary files a/DugunSalonuKiralama/.vs/DugunSalonuKiralama/FileContentIndex/5bca156e-dcae-4543-9a18-c9afb0167f07.vsidx and /dev/null differ
[1mdiff --git a/DugunSalonuKiralama/.vs/DugunSalonuKiralama/FileContentIndex/84b120ef-38b5-405a-9051-22e95cd298dc.vsidx b/DugunSalonuKiralama/.vs/DugunSalonuKiralama/FileContentIndex/84b120ef-38b5-405a-9051-22e95cd298dc.vsidx[m
[1mdeleted file mode 100644[m
[1mindex 959b732..0000000[m
Binary files a/DugunSalonuKiralama/.vs/DugunSalonuKiralama/FileContentIndex/84b120ef-38b5-405a-9051-22e95cd298dc.vsidx and /dev/null differ
[1mdiff --git a/DugunSalonuKiralama/.vs/DugunSalonuKiralama/FileContentIndex/b49764a3-ac7a-46b0-b1e4-a7973144d8a6.vsidx b/DugunSalonuKiralama/.vs/DugunSalonuKiralama/FileContentIndex/b49764a3-ac7a-46b0-b1e4-a7973144d8a6.vsidx[m
[1mdeleted file mode 100644[m
[1mindex a033b64..0000000[m
Binary files a/DugunSalonuKiralama/.vs/DugunSalonuKiralama/FileContentIndex/b49764a3-ac7a-46b0-b1e4-a7973144d8a6.vsidx and /dev/null differ
[1mdiff --git a/DugunSalonuKiralama/Core/DugunSalonuKiralama.Application/obj/Debug/net8.0/DugunSalonuKiralama.Application.AssemblyInfo.cs b/DugunSalonuKiralama/Core/DugunSalonuKiralama.Application/obj/Debug/net8.0/DugunSalonuKiralama.Application.AssemblyInfo.cs[m
[1mindex 81e670c..432b2db 100644[m
[1m--- a/DugunSalonuKiralama/Core/DugunSalonuKiralama.Application/obj/Debug/net8.0/DugunSalonuKiralama.Application.AssemblyInfo.cs[m
[1m+++ b/DugunSalonuKiralama/Core/DugunSalonuKiralama.Application/obj/Debug/net8.0/DugunSalonuKiralama.Application.AssemblyInfo.cs[m
[36m@@ -1,7 +1,6 @@[m
 //------------------------------------------------------------------------------[m
 // <auto-generated>[m
 //     This code was generated by a tool.[m
[31m-//     Runtime Version:4.0.30319.42000[m
 //[m
 //     Changes to this file may cause incorrect behavior and will be lost if[m
 //     the code is regenerated.[m
[36m@@ -14,10 +13,10 @@[m [musing System.Reflection;[m
 [assembly: System.Reflection.AssemblyCompanyAttribute("DugunSalonuKiralama.Application")][m
 [assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")][m
 [assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")][m
[31m-[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0+e8f9cfdef4f9a6680233d1edbfdcc8ecba7521e6")][m
[32m+[m[32m[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0+290d0b5649a7478b778ed14bbf1bdd02b0250bb0")][m
 [assembly: System.Reflection.AssemblyProductAttribute("DugunSalonuKiralama.Application")][m
 [assembly: System.Reflection.AssemblyTitleAttribute("DugunSalonuKiralama.Application")][m
 [assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")][m
 [m
[31m-// Generated by the MSBuild WriteCodeFragment class.[m
[32m+[m[32m// MSBuild WriteCodeFragment sınıfı tarafından oluşturuldu.[m
 [m
[1mdiff --git a/DugunSalonuKiralama/Core/DugunSalonuKiralama.Application/obj/Debug/net8.0/DugunSalonuKiralama.Application.AssemblyInfoInputs.cache b/DugunSalonuKiralama/Core/DugunSalonuKiralama.Application/obj/Debug/net8.0/DugunSalonuKiralama.Application.AssemblyInfoInputs.cache[m
[1mindex 1303391..5c8dd9c 100644[m
[1m--- a/DugunSalonuKiralama/Core/DugunSalonuKiralama.Application/obj/Debug/net8.0/DugunSalonuKiralama.Application.AssemblyInfoInputs.cache[m
[1m+++ b/DugunSalonuKiralama/Core/DugunSalonuKiralama.Application/obj/Debug/net8.0/DugunSalonuKiralama.Application.AssemblyInfoInputs.cache[m
[36m@@ -1 +1 @@[m
[31m-9db180b0b64a6f06bc1f04d7964f74d896a37d2e8556de4b9b385ba820ca96fd[m
[32m+[m[32maff0121983c533c6d53d5bff06f8a3a2fd550b28746f7efd2aaa46b2c96bf8dd[m
[1mdiff --git a/DugunSalonuKiralama/Core/DugunSalonuKiralama.Application/obj/Debug/net8.0/DugunSalonuKiralama.Application.GeneratedMSBuildEditorConfig.editorconfig b/DugunSalonuKiralama/Core/DugunSalonuKiralama.Application/obj/Debug/net8.0/DugunSalonuKiralama.Application.GeneratedMSBuildEditorConfig.editorconfig[m
[1mindex c54bcd9..a180be5 100644[m
[1m--- a/DugunSalonuKiralama/Core/DugunSalonuKiralama.Application/obj/Debug/net8.0/DugunSalonuKiralama.Application.GeneratedMSBuildEditorConfig.editorconfig[m
[1m+++ b/DugunSalonuKiralama/Core/DugunSalonuKiralama.Application/obj/Debug/net8.0/DugunSalonuKiralama.Application.GeneratedMSBuildEditorConfig.editorconfig[m
[36m@@ -8,8 +8,6 @@[m [mbuild_property.PlatformNeutralAssembly =[m
 build_property.EnforceExtendedAnalyzerRules = [m
 build_property._SupportedPlatformList = Linux,macOS,Windows[m
 build_property.RootNamespace = DugunSalonuKiralama.Application[m
[31m-build_property.ProjectDir = C:\Users\Anıl Enes torun\Documents\GitHub\MakineOgrenmeliDugunSalonuKiralama\DugunSalonuKiralama\Core\DugunSalonuKiralama.Application\[m
[32m+[m[32mbuild_property.ProjectDir = C:\Users\Yusuf ARAS\OneDrive\Belgeler\GitHub\MakineOgrenmeliDugunSalonuKiralama\DugunSalonuKiralama\Core\DugunSalonuKiralama.Application\[m
 build_property.EnableComHosting = [m
 build_property.EnableGeneratedComInterfaceComImportInterop = [m
[31m-build_property.EffectiveAnalysisLevelStyle = 8.0[m
[31m-build_property.EnableCodeStyleSeverity = [m
[1mdiff --git a/DugunSalonuKiralama/Core/DugunSalonuKiralama.Application/obj/Debug/net8.0/DugunSalonuKiralama.Application.assets.cache b/DugunSalonuKiralama/Core/DugunSalonuKiralama.Application/obj/Debug/net8.0/DugunSalonuKiralama.Application.assets.cache[m
[1mindex 42c45a9..b434328 100644[m
Binary files a/DugunSalonuKiralama/Core/DugunSalonuKiralama.Application/obj/Debug/net8.0/DugunSalonuKiralama.Application.assets.cache and b/DugunSalonuKiralama/Core/DugunSalonuKiralama.Application/obj/Debug/net8.0/DugunSalonuKiralama.Application.assets.cache differ
[1mdiff --git a/DugunSalonuKiralama/Core/DugunSalonuKiralama.Application/obj/Debug/net8.0/DugunSalonuKiralama.Application.csproj.AssemblyReference.cache b/DugunSalonuKiralama/Core/DugunSalonuKiralama.Application/obj/Debug/net8.0/DugunSalonuKiralama.Application.csproj.AssemblyReference.cache[m
[1mindex 2eb609c..ee87a38 100644[m
Binary files a/DugunSalonuKiralama/Core/DugunSalonuKiralama.Application/obj/Debug/net8.0/DugunSalonuKiralama.Application.csproj.AssemblyReference.cache and b/DugunSalonuKiralama/Core/DugunSalonuKiralama.Application/obj/Debug/net8.0/DugunSalonuKiralama.Application.csproj.AssemblyReference.cache differ
[1mdiff --git a/DugunSalonuKiralama/Core/DugunSalonuKiralama.Application/obj/Debug/net8.0/DugunSalonuKiralama.Application.csproj.CoreCompileInputs.cache b/DugunSalonuKiralama/Core/DugunSalonuKiralama.Application/obj/Debug/net8.0/DugunSalonuKiralama.Application.csproj.CoreCompileInputs.cache[m
[1mindex 3d50b20..4d039ed 100644[m
[1m--- a/DugunSalonuKiralama/Core/DugunSalonuKiralama.Application/obj/Debug/net8.0/DugunSalonuKiralama.Application.csproj.CoreCompileInputs.cache[m
[1m+++ b/DugunSalonuKiralama/Core/DugunSalonuKiralama.Application/obj/Debug/net8.0/DugunSalonuKiralama.Application.csproj.CoreCompileInputs.cache[m
[36m@@ -1 +1 @@[m
[31m-1054b4279bb564a32739af98a1815148106e1c1753dd9bcdbbd653c77803d949[m
[32m+[m[32m8db752c56c6f1db81b489b0cd80e2f789d39791ba7b9778f6858af125cfbddc6[m
[1mdiff --git a/DugunSalonuKiralama/Core/DugunSalonuKiralama.Application/obj/Debug/net8.0/DugunSalonuKiralama.Application.csproj.FileListAbsolute.txt b/DugunSalonuKiralama/Core/DugunSalonuKiralama.Application/obj/Debug/net8.0/DugunSalonuKiralama.Application.csproj.FileListAbsolute.txt[m
[1mindex a53fbc4..cb1bd62 100644[m
[1m--- a/DugunSalonuKiralama/Core/DugunSalonuKiralama.Application/obj/Debug/net8.0/DugunSalonuKiralama.Application.csproj.FileListAbsolute.txt[m
[1m+++ b/DugunSalonuKiralama/Core/DugunSalonuKiralama.Application/obj/Debug/net8.0/DugunSalonuKiralama.Application.csproj.FileListAbsolute.txt[m
[36m@@ -1,19 +1,3 @@[m
[31m-C:\Users\Yusuf ARAS\OneDrive\Belgeler\GitHub\MakineOgrenmeliDugunSalonuKiralama\DugunSalonuKiralama\Core\DugunSalonuKiralama.Application\bin\Debug\net8.0\DugunSalonuKiralama.Application.deps.json[m
[31m-C:\Users\Yusuf ARAS\OneDrive\Belgeler\GitHub\MakineOgrenmeliDugunSalonuKiralama\DugunSalonuKiralama\Core\DugunSalonuKiralama.Application\bin\Debug\net8.0\DugunSalonuKiralama.Application.dll[m
[31m-C:\Users\Yusuf ARAS\OneDrive\Belgeler\GitHub\MakineOgrenmeliDugunSalonuKiralama\DugunSalonuKiralama\Core\DugunSalonuKiralama.Application\bin\Debug\net8.0\DugunSalonuKiralama.Application.pdb[m
[31m-C:\Users\Yusuf ARAS\OneDrive\Belgeler\GitHub\MakineOgrenmeliDugunSalonuKiralama\DugunSalonuKiralama\Core\DugunSalonuKiralama.Application\bin\Debug\net8.0\DugunSalonuKiralama.Domain.dll[m
[31m-C:\Users\Yusuf ARAS\OneDrive\Belgeler\GitHub\MakineOgrenmeliDugunSalonuKiralama\DugunSalonuKiralama\Core\DugunSalonuKiralama.Application\bin\Debug\net8.0\DugunSalonuKiralama.Domain.pdb[m
[31m-C:\Users\Yusuf ARAS\OneDrive\Belgeler\GitHub\MakineOgrenmeliDugunSalonuKiralama\DugunSalonuKiralama\Core\DugunSalonuKiralama.Application\obj\Debug\net8.0\DugunSalonuKiralama.Application.csproj.AssemblyReference.cache[m
[31m-C:\Users\Yusuf ARAS\OneDrive\Belgeler\GitHub\MakineOgrenmeliDugunSalonuKiralama\DugunSalonuKiralama\Core\DugunSalonuKiralama.Application\obj\Debug\net8.0\DugunSalonuKiralama.Application.GeneratedMSBuildEditorConfig.editorconfig[m
[31m-C:\Users\Yusuf ARAS\OneDrive\Belgeler\GitHub\MakineOgrenmeliDugunSalonuKiralama\DugunSalonuKiralama\Core\DugunSalonuKiralama.Application\obj\Debug\net8.0\DugunSalonuKiralama.Application.AssemblyInfoInputs.cache[m
[31m-C:\Users\Yusuf ARAS\OneDrive\Belgeler\GitHub\MakineOgrenmeliDugunSalonuKiralama\DugunSalonuKiralama\Core\DugunSalonuKiralama.Application\obj\Debug\net8.0\DugunSalonuKiralama.Application.AssemblyInfo.cs[m
[31m-C:\Users\Yusuf ARAS\OneDrive\Belgeler\GitHub\MakineOgrenmeliDugunSalonuKiralama\DugunSalonuKiralama\Core\DugunSalonuKiralama.Application\obj\Debug\net8.0\DugunSalonuKiralama.Application.csproj.CoreCompileInputs.cache[m
[31m-C:\Users\Yusuf ARAS\OneDrive\Belgeler\GitHub\MakineOgrenmeliDugunSalonuKiralama\DugunSalonuKiralama\Core\DugunSalonuKiralama.Application\obj\Debug\net8.0\DugunSalonuKiralama.Application.sourcelink.json[m
[31m-C:\Users\Yusuf ARAS\OneDrive\Belgeler\GitHub\MakineOgrenmeliDugunSalonuKiralama\DugunSalonuKiralama\Core\DugunSalonuKiralama.Application\obj\Debug\net8.0\DugunSalonuKiralama.Application.csproj.CopyComplete[m
[31m-C:\Users\Yusuf ARAS\OneDrive\Belgeler\GitHub\MakineOgrenmeliDugunSalonuKiralama\DugunSalonuKiralama\Core\DugunSalonuKiralama.Application\obj\Debug\net8.0\DugunSalonuKiralama.Application.dll[m
[31m-C:\Users\Yusuf ARAS\OneDrive\Belgeler\GitHub\MakineOgrenmeliDugunSalonuKiralama\DugunSalonuKiralama\Core\DugunSalonuKiralama.Application\obj\Debug\net8.0\refint\DugunSalonuKiralama.Application.dll[m
[31m-C:\Users\Yusuf ARAS\OneDrive\Belgeler\GitHub\MakineOgrenmeliDugunSalonuKiralama\DugunSalonuKiralama\Core\DugunSalonuKiralama.Application\obj\Debug\net8.0\DugunSalonuKiralama.Application.pdb[m
[31m-C:\Users\Yusuf ARAS\OneDrive\Belgeler\GitHub\MakineOgrenmeliDugunSalonuKiralama\DugunSalonuKiralama\Core\DugunSalonuKiralama.Application\obj\Debug\net8.0\ref\DugunSalonuKiralama.Application.dll[m
 C:\Users\Anıl Enes torun\Documents\GitHub\MakineOgrenmeliDugunSalonuKiralama\DugunSalonuKiralama\Core\DugunSalonuKiralama.Application\bin\Debug\net8.0\DugunSalonuKiralama.Application.deps.json[m
 C:\Users\Anıl Enes torun\Documents\GitHub\MakineOgrenmeliDugunSalonuKiralama\DugunSalonuKiralama\Core\DugunSalonuKiralama.Application\bin\Debug\net8.0\DugunSalonuKiralama.Application.dll[m
 C:\Users\Anıl Enes torun\Documents\GitHub\MakineOgrenmeliDugunSalonuKiralama\DugunSalonuKiralama\Core\DugunSalonuKiralama.Application\bin\Debug\net8.0\DugunSalonuKiralama.Application.pdb[m
[36m@@ -30,3 +14,19 @@[m [mC:\Users\Anıl Enes torun\Documents\GitHub\MakineOgrenmeliDugunSalonuKiralama\Du[m
 C:\Users\Anıl Enes torun\Documents\GitHub\MakineOgrenmeliDugunSalonuKiralama\DugunSalonuKiralama\Core\DugunSalonuKiralama.Application\obj\Debug\net8.0\refint\DugunSalonuKiralama.Application.dll[m
 C:\Users\Anıl Enes torun\Documents\GitHub\MakineOgrenmeliDugunSalonuKiralama\DugunSalonuKiralama\Core\DugunSalonuKiralama.Application\obj\Debug\net8.0\DugunSalonuKiralama.Application.pdb[m
 C:\Users\Anıl Enes torun\Documents\GitHub\MakineOgrenmeliDugunSalonuKiralama\DugunSalonuKiralama\Core\DugunSalonuKiralama.Application\obj\Debug\net8.0\ref\DugunSalonuKiralama.Application.dll[m
[32m+[m[32mC:\Users\Yusuf ARAS\OneDrive\Belgeler\GitHub\MakineOgrenmeliDugunSalonuKiralama\DugunSalonuKiralama\Core\DugunSalonuKiralama.Application\bin\Debug\net8.0\DugunSalonuKiralama.Application.deps.json[m
[32m+[m[32mC:\Users\Yusuf ARAS\OneDrive\Belgeler\GitHub\MakineOgrenmeliDugunSalonuKiralama\DugunSalonuKiralama\Core\DugunSalonuKiralama.Application\bin\Debug\net8.0\DugunSalonuKiralama.Application.dll[m
[32m+[m[32mC:\Users\Yusuf ARAS\OneDrive\Belgeler\GitHub\MakineOgrenmeliDugunSalonuKiralama\DugunSalonuKiralama\Core\DugunSalonuKiralama.Application\bin\Debug\net8.0\DugunSalonuKiralama.Application.pdb[m
[32m+[m[32mC:\Users\Yusuf ARAS\OneDrive\Belgeler\GitHub\MakineOgrenmeliDugunSalonuKiralama\DugunSalonuKiralama\Core\DugunSalonuKiralama.Application\bin\Debug\net8.0\DugunSalonuKiralama.Domain.dll[m
[32m+[m[32mC:\Users\Yusuf ARAS\OneDrive\Belgeler\GitHub\MakineOgrenmeliDugunSalonuKiralama\DugunSalonuKiralama\Core\DugunSalonuKiralama.Application\bin\Debug\net8.0\DugunSalonuKiralama.Domain.pdb[m
[32m+[m[32mC:\Users\Yusuf ARAS\OneDrive\Belgeler\GitHub\MakineOgrenmeliDugunSalonuKiralama\DugunSalonuKiralama\Core\DugunSalonuKiralama.Application\obj\Debug\net8.0\DugunSalonuKiralama.Application.csproj.AssemblyReference.cache[m
[32m+[m[32mC:\Users\Yusuf ARAS\OneDrive\Belgeler\GitHub\MakineOgrenmeliDugunSalonuKiralama\DugunSalonuKiralama\Core\DugunSalonuKiralama.Application\obj\Debug\net8.0\DugunSalonuKiralama.Application.GeneratedMSBuildEditorConfig.editorconfig[m
[32m+[m[32mC:\Users\Yusuf ARAS\OneDrive\Belgeler\GitHub\MakineOgrenmeliDugunSalonuKiralama\DugunSalonuKiralama\Core\DugunSalonuKiralama.Application\obj\Debug\net8.0\DugunSalonuKiralama.Application.AssemblyInfoInputs.cache[m
[32m+[m[32mC:\Users\Yusuf ARAS\OneDrive\Belgeler\GitHub\MakineOgrenmeliDugunSalonuKiralama\DugunSalonuKiralama\Core\DugunSalonuKiralama.Application\obj\Debug\net8.0\DugunSalonuKiralama.Application.AssemblyInfo.cs[m
[32m+[m[32mC:\Users\Yusuf ARAS\OneDrive\Belgeler\GitHub\MakineOgrenmeliDugunSalonuKiralama\DugunSalonuKiralama\Core\DugunSalonuKiralama.Application\obj\Debug\net8.0\DugunSalonuKiralama.Application.csproj.CoreCompileInputs.cache[m
[32m+[m[32mC:\Users\Yusuf ARAS\OneDrive\Belgeler\GitHub\MakineOgrenmeliDugunSalonuKiralama\DugunSalonuKiralama\Core\DugunSalonuKiralama.Application\obj\Debug\net8.0\DugunSalonuKiralama.Application.sourcelink.json[m
[32m+[m[32mC:\Users\Yusuf ARAS\OneDrive\Belgeler\GitHub\MakineOgrenmeliDugunSalonuKiralama\DugunSalonuKiralama\Core\DugunSalonuKiralama.Application\obj\Debug\net8.0\DugunSalonuKiralama.Application.csproj.CopyComplete[m
[32m+[m[32mC:\Users\Yusuf ARAS\OneDrive\Belgeler\GitHub\MakineOgrenmeliDugunSalonuKiralama\DugunSalonuKiralama\Core\DugunSalon